# OASIS RESEARCH FUNDING
# Apoya la investigación científica de la Termodinámica Computacional.
# Estas donaciones financian el desarrollo de código abierto y la publicación de papers.
# No otorgan derechos comerciales ni futuros.

github: [oasis-swarm]
custom: ["https://gitcoin.co/grants/new", "https://app.optimism.io/rpgf"]
lat_long: "33zJ9jmWYWe6JmHuw8aHoJqKQGFqdz1qVE"


